<?php
if (!defined('ABSPATH')) {
    exit;
}
return array(
	'PurolatorExpress9AM'                    => 'Purolator Express 9AM',
	'PurolatorExpress10:30AM'                    => 'Purolator Express 10:30AM',
	'PurolatorExpress'                    => 'Purolator Express',
	'PurolatorExpressEnvelope9AM'                    => 'Purolator Express Envelope 9AM',
	'PurolatorExpressEnvelope10:30AM'                    => 'Purolator Express Envelope 10:30AM',
	'PurolatorExpressEnvelope'                    => 'Purolator Express Envelope',
	'PurolatorExpressPack9AM'                    => 'Purolator Express Pack 9AM',
	'PurolatorExpressPack10:30AM'                    => 'Purolator Express Pack 10:30AM',
	'PurolatorExpressPack'                    => 'Purolator Express Pack',
	'PurolatorExpressBox9AM'                    => 'Purolator Express Box 9AM',
	'PurolatorExpressBox10:30AM'                    => 'Purolator Express Box 10:30AM',
	'PurolatorExpressBox'                    => 'Purolator Express Box',
	'PurolatorGround'                    => 'Purolator Ground',
	'PurolatorGroundDistribution'                    => 'Purolator Ground Distribution',
	'PurolatorExpressU.S.9AM'                    => 'Purolator Express U.S. 9AM',
	'PurolatorExpressU.S.10:30AM'                    => 'Purolator Express U.S. 10:30 AM',
	'PurolatorExpressU.S.'                    => 'Purolator Express U.S.',
	'PurolatorExpressEvening' => 'Purolator Express Evening',
	'PurolatorExpressEnvelopeEvening' => 'Purolator Express Envelope Evening',
	'PurolatorExpressPackEvening' => 'Purolator Express Pack Evening',
	'PurolatorExpressBoxEvening' => 'Purolator Express Box Evening',
	'PurolatorGround9AM' => 'Purolator Ground 9AM',
	'PurolatorGround10:30AM' => 'Purolator Ground 10:30AM',
	'PurolatorGroundEvening' => 'Purolator Ground Evening',
	'PurolatorExpressU.S.12:00' => 'Purolator Express U.S. 12:00',
	'PurolatorExpressEnvelopeU.S.' => 'Purolator Express Envelope U.S.',
	'PurolatorExpressU.S.Envelope9AM' => 'Purolator Express U.S. Envelope 9AM',
	'PurolatorExpressU.S.Envelope10:30AM' => 'Purolator Express U.S. Envelope 10:30AM',
	'PurolatorExpressU.S.Envelope12:00' => 'Purolator Express U.S. Envelope 12:00',
	'PurolatorExpressPackU.S.' => 'Purolator Express Pack U.S.',
	'PurolatorExpressU.S.Pack9AM' => 'Purolator Express U.S. Pack 9AM',
	'PurolatorExpressU.S.Pack10:30AM' => 'Purolator Express U.S. Pack 10:30AM',
	'PurolatorExpressU.S.Pack12:00' => 'Purolator Express U.S. Pack 12:00',
	'PurolatorExpressBoxU.S.' => 'Purolator Express Box U.S.',
	'PurolatorExpressU.S.Box9AM' => 'Purolator Express U.S. Box 9AM',
	'PurolatorExpressU.S.Box10:30AM' => 'Purolator Express U.S. Box 10:30AM',
	'PurolatorExpressU.S.Box12:00' => 'Purolator Express U.S. Box 12:00',
	'PurolatorGroundU.S.' => 'Purolator Ground U.S.',
	'PurolatorExpressInternational' => 'Purolator Express International',
	'PurolatorExpressInternational9AM' => 'Purolator Express International 9AM ',
	'PurolatorExpressInternational10:30AM' => 'Purolator Express International 10:30AM',
	'PurolatorExpressInternational12:00' => 'Purolator Express International 12:00',
	'PurolatorExpressEnvelopeInternational' => 'Purolator Express Envelope International',
	'PurolatorExpressInternationalEnvelope9AM' => 'Purolator Express International Envelope 9AM',
	'PurolatorExpressInternationalEnvelope10:30AM' => 'Purolator Express International Envelope 10:30AM',
	'PurolatorExpressInternationalEnvelope12:00' => 'Purolator Express International Envelope 12:00',
	'PurolatorExpressPackInternational' => 'Purolator Express Pack International',
	'PurolatorExpressInternationalPack9AM' => 'Purolator Express International Pack 9AM',
	'PurolatorExpressInternationalPack10:30AM' => 'Purolator Express International Pack 10:30AM',
	'PurolatorExpressInternationalPack12:00' => 'Purolator Express International Pack 12:00',
	'PurolatorExpressBoxInternational' => 'Purolator Express Box International',
	'PurolatorExpressInternationalBox9AM' => 'Purolator Express International Box 9AM',
	'PurolatorExpressInternationalBox10:30AM' => 'Purolator Express International Box 10:30AM',
	'PurolatorExpressInternationalBox12:00' => 'Purolator Express International Box 12:00',
	'PurolatorExpress12PM' => 'Purolator Express 12PM',
	'PurolatorExpressEnvelope12PM' => 'Purolator Express Envelope 12PM',
	'PurolatorExpressPack12PM' => 'Purolator Express Pack 12PM',
	'PurolatorExpressBox12PM' => 'Purolator Express Box 12PM',
);